// AUTO-GENERATED v2 question bank: rebalanced difficulty (fewer EASY, more HARD)
// and hardened distractors for a well-catechized 15-30 audience.
import { QuestionSeed } from '../src/lib/types';

export const QUESTION_BANK: QuestionSeed[] = [
  {
    "id": "72H-01",
    "category": "72H",
    "question_text": "U kojoj je zemlji započela međunarodna ideja projekta „72 sata bez kompromisa“?",
    "option_a": "Austrija",
    "option_b": "Njemačka",
    "option_c": "Švicarska",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "72H-02",
    "category": "72H",
    "question_text": "Koje je godine projekt prvi put proveden u Hrvatskoj?",
    "option_a": "2010.",
    "option_b": "2014.",
    "option_c": "2018.",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "72H-03",
    "category": "72H",
    "question_text": "U kojem je hrvatskom gradu projekt prvi put proveden?",
    "option_a": "Zagreb",
    "option_b": "Split",
    "option_c": "Osijek",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "72H-04",
    "category": "72H",
    "question_text": "Koliko ukupno traje sam projekt „72 sata bez kompromisa“?",
    "option_a": "48 sati",
    "option_b": "72 sata",
    "option_c": "96 sati",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "72H-05",
    "category": "72H",
    "question_text": "Kojoj je dobnoj skupini projekt prvenstveno namijenjen?",
    "option_a": "12 – 25 godina",
    "option_b": "15 – 35 godina",
    "option_c": "18 – 40 godina",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "72H-06",
    "category": "72H",
    "question_text": "Po čemu je projekt posebno prepoznatljiv u odnosu na klasično volontiranje?",
    "option_a": "Sudionici sami unaprijed biraju konkretnu akciju i organizaciju",
    "option_b": "Sudionici se prijavljuju bez odabira konkretne volonterske akcije",
    "option_c": "Sudionici se raspoređuju isključivo prema mjestu stanovanja",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-07",
    "category": "72H",
    "question_text": "Što sudionici projekta prvenstveno daruju drugima, prema temeljnoj ideji projekta?",
    "option_a": "Novac i materijalne donacije",
    "option_b": "Svoje vrijeme, sposobnosti i talente",
    "option_c": "Isključivo stručno certificirano znanje",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-08",
    "category": "72H",
    "question_text": "Koje su tri glavne skupine aktivnosti tipične za akcije unutar projekta?",
    "option_a": "Radne, socijalne i ekološke",
    "option_b": "Isključivo sportske i rekreacijske",
    "option_c": "Isključivo katehetske i liturgijske",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-09",
    "category": "72H",
    "question_text": "Koja je temeljna vrijednost na kojoj projekt počiva?",
    "option_a": "Natjecanje među sudionicima",
    "option_b": "Solidarnost i volontiranje",
    "option_c": "Prikupljanje sredstava za organizatore",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-10",
    "category": "72H",
    "question_text": "Zašto se projekt naziva „bez kompromisa“?",
    "option_a": "Jer volonter smije odbiti zadatak koji mu nije po volji",
    "option_b": "Jer sudionik svoje vrijeme i sposobnosti stavlja na raspolaganje bez unaprijed odabranog zadatka",
    "option_c": "Jer se projekt ne smije prilagođavati lokalnim potrebama",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-11",
    "category": "72H",
    "question_text": "Kako se projekt širio u Hrvatskoj nakon prvog izdanja u Splitu?",
    "option_a": "Ostao je ograničen isključivo na grad u kojem je pokrenut",
    "option_b": "Postupno se proširio u druge hrvatske gradove i općine",
    "option_c": "Preselio se trajno u drugi grad domaćin",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-12",
    "category": "72H",
    "question_text": "Koja je glavna ideja projekta u jednoj rečenici?",
    "option_a": "Prikupiti što više volonterskih sati za osobnu evidenciju",
    "option_b": "Konkretno pomoći ljudima i zajednici vlastitim vremenom i sposobnostima",
    "option_c": "Organizirati natjecanje u fizičkoj spremi među mladima",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-13",
    "category": "72H",
    "question_text": "Što, prema opisu projekta, volonter može dobiti kroz sudjelovanje, osim iskustva pomaganja?",
    "option_a": "Isključivo novčanu naknadu za rad",
    "option_b": "Nova poznanstva, razvoj vještina i priliku za služenje drugima",
    "option_c": "Automatsku diplomu srednjoškolskog obrazovanja",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-14",
    "category": "72H",
    "question_text": "Koji pojam najbolje opisuje odnos projekta prema unaprijed nepoznatom zadatku?",
    "option_a": "Beskompromisnost",
    "option_b": "Ekskluzivnost",
    "option_c": "Individualizam",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-15",
    "category": "72H",
    "question_text": "Zašto sudionik unaprijed ne zna točnu akciju na kojoj će raditi?",
    "option_a": "Da bi se usredotočio na spremnost pomoći, a ne na osobne preferencije",
    "option_b": "Da organizatori ne moraju unaprijed pripremati akcije",
    "option_c": "Da bi svi sudionici radili identičan posao",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-16",
    "category": "72H",
    "question_text": "Koga projekt prvenstveno želi potaknuti na volontiranje?",
    "option_a": "Umirovljenike",
    "option_b": "Mlade",
    "option_c": "Isključivo zaposlenike javnih ustanova",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-17",
    "category": "72H",
    "question_text": "Koji naziv najbolje opisuje osobe koje sudjeluju u konkretnim akcijama projekta?",
    "option_a": "Volonteri",
    "option_b": "Delegati",
    "option_c": "Natjecatelji saveza",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-18",
    "category": "72H",
    "question_text": "Koje od navedenog NIJE tipičan cilj projekta?",
    "option_a": "Pomoć potrebitima",
    "option_b": "Jačanje zajedništva",
    "option_c": "Povećanje individualne financijske dobiti sudionika",
    "correct_answer": "C",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-19",
    "category": "72H",
    "question_text": "Koja je razlika između sudjelovanja u ovom projektu i klasičnog jednokratnog doniranja novca humanitarnoj organizaciji?",
    "option_a": "Sudionik osobno i izravno daje svoje vrijeme i rad, a ne samo novčana sredstva",
    "option_b": "Sudionik isključivo prikuplja novac za treću stranu",
    "option_c": "Nema nikakve razlike, riječ je o istovjetnom obliku pomoći",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-20",
    "category": "72H",
    "question_text": "Što je, prema duhu projekta, posebno važno kod samog čina volontiranja?",
    "option_a": "Da volonter bira isključivo aktivnosti koje su mu najlakše",
    "option_b": "Da je spreman svoje sposobnosti staviti u službu drugih, bez unaprijed postavljenih uvjeta",
    "option_c": "Da mora imati prethodno certificirano iskustvo u volontiranju",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "72H-21",
    "category": "72H",
    "question_text": "U kojem je hrvatskom gradu pokrenut prvi lokalni „72 sata bez kompromisa“ 2014. godine?",
    "option_a": "Split",
    "option_b": "Zagreb",
    "option_c": "Dubrovnik",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-22",
    "category": "72H",
    "question_text": "Ako je prvo hrvatsko izdanje bilo 2014., koliko je punih godina projekt prisutan u Hrvatskoj računajući do izdanja 2026.?",
    "option_a": "10",
    "option_b": "12",
    "option_c": "14",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-23",
    "category": "72H",
    "question_text": "Koji je od ponuđenih opisa najbliži duhu projekta „bez kompromisa“?",
    "option_a": "„Prvo biram što meni najbolje odgovara.“",
    "option_b": "„Dajem svoje vrijeme i sposobnosti tamo gdje su potrebne, bez unaprijed postavljenog izbora.“",
    "option_c": "„Pomažem samo ako mi je zadatak unaprijed detaljno poznat.“",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-24",
    "category": "72H",
    "question_text": "Prema podacima o izdanju 2025. godine, koliko je hrvatskih gradova i općina bilo uključeno?",
    "option_a": "12",
    "option_b": "22",
    "option_c": "32",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-25",
    "category": "72H",
    "question_text": "Koji je bio službeni slogan izdanja projekta u 2025. godini?",
    "option_a": "Pruži nadu",
    "option_b": "Vjeruj više",
    "option_c": "Budi promjena",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-26",
    "category": "72H",
    "question_text": "U kojem se točnom periodu listopada 2025. održalo to izdanje projekta?",
    "option_a": "1. – 4. listopada",
    "option_b": "16. – 19. listopada",
    "option_c": "24. – 27. listopada",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-27",
    "category": "72H",
    "question_text": "Koja je bila posebnost samog rasporeda volonterskih akcija u izdanju 2025.?",
    "option_a": "Sudionici su svakodnevno mogli mijenjati akciju po želji",
    "option_b": "Konkretna akcija otkrivala se sudionicima tek na samom početku",
    "option_c": "Svi su sudionici tog izdanja radili isključivo na jednom mjestu",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-28",
    "category": "72H",
    "question_text": "Koji je predmet bio prepoznatljiv vizualni simbol pripadnosti projektu u izdanju 2025.?",
    "option_a": "Zelena majica",
    "option_b": "Crvena kapa",
    "option_c": "Plavi šal",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-29",
    "category": "72H",
    "question_text": "Ako je dobna granica sudionika 15 – 35 godina, a izdanje 2025. brojalo je 22 grada i općine, koji je od sljedeća dva podatka točan opis tog izdanja?",
    "option_a": "Dobna granica 15 – 35, broj gradova/općina 22",
    "option_b": "Dobna granica 18 – 40, broj gradova/općina 22",
    "option_c": "Dobna granica 15 – 35, broj gradova/općina 12",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "72H-30",
    "category": "72H",
    "question_text": "Ako se prijaviš na 72H, koja je, prema temeljnoj ideji projekta, najvažnija stvar koju pristaješ darovati drugima?",
    "option_a": "Svoje vrijeme i sposobnosti",
    "option_b": "Isključivo financijska sredstva",
    "option_c": "Isključivo stručnu opremu koju posjeduješ",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-01",
    "category": "MARIJA_BISTRICA",
    "question_text": "U kojoj se hrvatskoj regiji nalazi Marija Bistrica?",
    "option_a": "Istra",
    "option_b": "Hrvatsko zagorje",
    "option_c": "Baranja",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "MB-02",
    "category": "MARIJA_BISTRICA",
    "question_text": "Kako se zove hrvatsko nacionalno marijansko svetište u Mariji Bistrici?",
    "option_a": "Svetište Majke Božje Bistričke",
    "option_b": "Svetište Gospe od Mora",
    "option_c": "Svetište Kraljice Mira",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "MB-03",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koji je papa 1998. godine u Mariji Bistrici proglasio blaženim kardinala Alojzija Stepinca?",
    "option_a": "Ivan Pavao II.",
    "option_b": "Benedikt XVI.",
    "option_c": "Pavao VI.",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "MB-04",
    "category": "MARIJA_BISTRICA",
    "question_text": "Kako se danas zove veliki trg pred svetištem u Mariji Bistrici?",
    "option_a": "Trg bana Jelačića",
    "option_b": "Trg pape Ivana Pavla II.",
    "option_c": "Trg kardinala Stepinca",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-05",
    "category": "MARIJA_BISTRICA",
    "question_text": "U kojem je stoljeću, prema predaji, izrezbaren kip Majke Božje Bistričke?",
    "option_a": "12. stoljeću",
    "option_b": "15. stoljeću",
    "option_c": "19. stoljeću",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-06",
    "category": "MARIJA_BISTRICA",
    "question_text": "Kako se kip Majke Božje Bistričke tradicionalno svrstava po ikonografskom tipu?",
    "option_a": "Među Bijele Madone",
    "option_b": "Među Crne Madone",
    "option_c": "Među Krunjene Madone bez posebnog tipa",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-07",
    "category": "MARIJA_BISTRICA",
    "question_text": "Odakle je kip Majke Božje Bistričke prenesen u Mariju Bistricu 1545. godine?",
    "option_a": "S Vinskog Vrha",
    "option_b": "S Trsata",
    "option_c": "Iz Sinja",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-08",
    "category": "MARIJA_BISTRICA",
    "question_text": "Zbog čega je kip 1545. godine prenesen s Vinskog Vrha u Mariju Bistricu?",
    "option_a": "Zbog opasnosti od turskih napada",
    "option_b": "Zbog požara u dotadašnjem svetištu",
    "option_c": "Zbog potresa koji je oštetio kapelu",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-09",
    "category": "MARIJA_BISTRICA",
    "question_text": "Što se, prema predaji o povijesti kipa, dogodilo nakon njegova premještanja u župnu crkvu?",
    "option_a": "Dva je puta bio zazidan i dva puta ponovno pronađen",
    "option_b": "Bio je zauvijek izgubljen tijekom osmanskih napada",
    "option_c": "Bio je prenesen u Rim na čuvanje",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-10",
    "category": "MARIJA_BISTRICA",
    "question_text": "Kako se zove poznati križni put s postajama iznad svetišta u Mariji Bistrici?",
    "option_a": "Bistrička Kalvarija",
    "option_b": "Gornjogradska Kalvarija",
    "option_c": "Hrvatska Kalvarija",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-13",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koje je godine kip Majke Božje Bistričke svečano (kanonski) okrunjen, čime je svetište potvrđeno kao osobito značajno mjesto štovanja?",
    "option_a": "1715.",
    "option_b": "1815.",
    "option_c": "1915.",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-14",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koje tradicionalne dječje rukotvorine Hrvatskog zagorja, usko povezane s hodočasničkom baštinom Marije Bistrice, imaju UNESCO status?",
    "option_a": "Drvene dječje igračke",
    "option_b": "Keramički tanjuri",
    "option_c": "Svilene marame",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MB-15",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koje je godine tradicionalna izrada dječjih drvenih igračaka Hrvatskog zagorja upisana na UNESCO-ov reprezentativni popis nematerijalne baštine?",
    "option_a": "1999.",
    "option_b": "2009.",
    "option_c": "2019.",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-16",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koje se vrste drva prema tradiciji najčešće koriste za izradu zagorskih drvenih igračaka?",
    "option_a": "Vrba, lipa, bukva i javor",
    "option_b": "Isključivo maslina i badem",
    "option_c": "Isključivo hrast i bor",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-17",
    "category": "MARIJA_BISTRICA",
    "question_text": "Tko prema tradicionalnoj podjeli posla najčešće izrađuje, a tko najčešće oslikava zagorske dječje igračke?",
    "option_a": "Žene ih izrađuju, muškarci ih oslikavaju",
    "option_b": "Muškarci ih izrađuju, žene ih najvećim dijelom oslikavaju",
    "option_c": "Cijeli proces isključivo obavljaju djeca u obiteljskoj radionici",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-18",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koje je kulturno umijeće, usko vezano uz licitarsko srce kao simbol hrvatske hodočasničke baštine, upisano na UNESCO-ov popis 2010. godine?",
    "option_a": "Umijeće izrade medičarskih proizvoda (licitara) iz sjeverne Hrvatske",
    "option_b": "Umijeće izrade čipke na otoku Pagu",
    "option_c": "Klapsko pjevanje",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-19",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koji je arhitekt krajem 19. stoljeća vodio veliku obnovu i pregradnju svetišne crkve u Mariji Bistrici u neogotičkom stilu?",
    "option_a": "Herman Bollé",
    "option_b": "Viktor Kovačić",
    "option_c": "Vjekoslav Bastl",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-20",
    "category": "MARIJA_BISTRICA",
    "question_text": "Ako je kip prenesen 1545., a kanonski okrunjen 1715., koliko je godina prošlo između ta dva događaja?",
    "option_a": "100",
    "option_b": "150",
    "option_c": "170",
    "correct_answer": "C",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-21",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koje geste/tvrdnje najtočnije opisuje zašto se licitari i drvene igračke smatraju važnima za identitet Marije Bistrice?",
    "option_a": "Predstavljaju dio lokalne hodočasničke i kulturne baštine kraja",
    "option_b": "Nastali su tek nakon 2000. godine kao suvenirski proizvod",
    "option_c": "Riječ je isključivo o turističkom proizvodu bez ikakve tradicije",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MB-22",
    "category": "MARIJA_BISTRICA",
    "question_text": "Koji naziv nosi svetkovina 15. kolovoza koja se u Mariji Bistrici slavi kao najveće godišnje hodočašće?",
    "option_a": "Uznesenje Blažene Djevice Marije (Velika Gospa)",
    "option_b": "Rođenje Blažene Djevice Marije (Mala Gospa)",
    "option_c": "Bezgrješno začeće",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-01",
    "category": "BIBLIJA",
    "question_text": "Koja je prva knjiga Novoga zavjeta?",
    "option_a": "Djela apostolska",
    "option_b": "Evanđelje po Mateju",
    "option_c": "Poslanica Rimljanima",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "BIB-02",
    "category": "BIBLIJA",
    "question_text": "Tko je krstio Isusa u rijeci Jordanu?",
    "option_a": "Ivan Krstitelj",
    "option_b": "Petar",
    "option_c": "Ivan evanđelist",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "BIB-03",
    "category": "BIBLIJA",
    "question_text": "Koliko evanđelja sadrži kanon Novoga zavjeta?",
    "option_a": "3",
    "option_b": "4",
    "option_c": "5",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "BIB-04",
    "category": "BIBLIJA",
    "question_text": "Koja se tri evanđelja nazivaju „sinoptičkima“ zbog sličnog sadržaja i strukture?",
    "option_a": "Matej, Marko i Luka",
    "option_b": "Matej, Marko i Ivan",
    "option_c": "Marko, Luka i Ivan",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-05",
    "category": "BIBLIJA",
    "question_text": "Koji je prorok, prema Prvoj knjizi o Samuelu, pomazao Davida za kralja?",
    "option_a": "Samuel",
    "option_b": "Natan",
    "option_c": "Ilija",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-07",
    "category": "BIBLIJA",
    "question_text": "Koja se novozavjetna knjiga prema mišljenju većine biblicista smatra najranije napisanom?",
    "option_a": "Prva poslanica Solunjanima",
    "option_b": "Evanđelje po Marku",
    "option_c": "Otkrivenje",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-08",
    "category": "BIBLIJA",
    "question_text": "Koliko knjiga broji Stari zavjet u katoličkom kanonu, uključujući deuterokanonske knjige?",
    "option_a": "39",
    "option_b": "46",
    "option_c": "51",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-09",
    "category": "BIBLIJA",
    "question_text": "Koji je apostol napisao najveći broj novozavjetnih poslanica?",
    "option_a": "Petar",
    "option_b": "Pavao",
    "option_c": "Ivan",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-10",
    "category": "BIBLIJA",
    "question_text": "Koji je apostol, prema predaji, propovijedao u Indiji i ondje mučenički umro?",
    "option_a": "Toma",
    "option_b": "Bartolomej",
    "option_c": "Filip",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-12",
    "category": "BIBLIJA",
    "question_text": "Koliko ukupno psalama sadrži starozavjetna Knjiga psalama?",
    "option_a": "100",
    "option_b": "150",
    "option_c": "175",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-14",
    "category": "BIBLIJA",
    "question_text": "Koje je bilo Isusovo prvo čudo prema Ivanovu evanđelju?",
    "option_a": "Umnoženje kruha",
    "option_b": "Pretvaranje vode u vino u Kani",
    "option_c": "Uskrsnuće Lazara",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-15",
    "category": "BIBLIJA",
    "question_text": "Za koliko srebrnjaka je Juda Iškariotski, prema evanđeoskom izvještaju, izdao Isusa?",
    "option_a": "10",
    "option_b": "30",
    "option_c": "50",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "BIB-16",
    "category": "BIBLIJA",
    "question_text": "Koje je hebrejsko ime kojim se Bog objavljuje Mojsiju kod gorućeg grma, u prijevodu „Ja jesam koji jesam“?",
    "option_a": "Elohim",
    "option_b": "JHWH (Jahve)",
    "option_c": "Adonai",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-17",
    "category": "BIBLIJA",
    "question_text": "Koji je grčki pojam u izvorniku Novoga zavjeta za „radosnu vijest“, iz kojeg dolazi riječ „evanđelje“?",
    "option_a": "Kerygma",
    "option_b": "Euangelion",
    "option_c": "Didache",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-18",
    "category": "BIBLIJA",
    "question_text": "Čije se pavlovsko autorstvo među novozavjetnim poslanicama danas najviše osporava u biblijskoj znanosti?",
    "option_a": "Poslanica Hebrejima",
    "option_b": "Poslanica Rimljanima",
    "option_c": "Poslanica Galaćanima",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-19",
    "category": "BIBLIJA",
    "question_text": "Kojim grčkim pojmom Ivanovo evanđelje označava Krista u svom proslovu („U početku bijaše Riječ...“)?",
    "option_a": "Logos",
    "option_b": "Pneuma",
    "option_c": "Sofia",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-20",
    "category": "BIBLIJA",
    "question_text": "Koliko poglavlja Knjige Postanka obuhvaća pripovijest o potopu, od najave do Noina izlaska iz arke?",
    "option_a": "Dva poglavlja",
    "option_b": "Četiri poglavlja",
    "option_c": "Šest poglavlja",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-21",
    "category": "BIBLIJA",
    "question_text": "Koji se novozavjetni redak tradicionalno naziva „malim evanđeljem“ jer sažima cijelu poruku spasenja?",
    "option_a": "Iv 3, 16",
    "option_b": "Rim 8, 28",
    "option_c": "1 Kor 13, 4",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-22",
    "category": "BIBLIJA",
    "question_text": "Koja se novozavjetna knjiga u biblijskoj znanosti najčešće smatra kronološki posljednjom napisanom knjigom kanona?",
    "option_a": "Otkrivenje",
    "option_b": "Ivanovo evanđelje",
    "option_c": "Druga Petrova poslanica",
    "correct_answer": "C",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "BIB-23",
    "category": "BIBLIJA",
    "question_text": "Koliko poglavlja ukupno broji Knjiga Otkrivenja?",
    "option_a": "20",
    "option_b": "22",
    "option_c": "24",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-01",
    "category": "VJERA",
    "question_text": "Koliko sakramenata priznaje Katolička Crkva?",
    "option_a": "5",
    "option_b": "7",
    "option_c": "9",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "VJERA-02",
    "category": "VJERA",
    "question_text": "Koji sakrament uvodi osobu u kršćansku zajednicu i prima se samo jednom u životu?",
    "option_a": "Krštenje",
    "option_b": "Ispovijed",
    "option_c": "Bolesničko pomazanje",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "VJERA-03",
    "category": "VJERA",
    "question_text": "Koje liturgijsko razdoblje broji unatrag prema Uskrsu i traje 40 dana pokore?",
    "option_a": "Došašće",
    "option_b": "Korizma",
    "option_c": "Vazmeno vrijeme",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "VJERA-04",
    "category": "VJERA",
    "question_text": "Koliko dana traje vazmeno (uskrsno) vrijeme, od Uskrsa do Duhova?",
    "option_a": "40 dana",
    "option_b": "50 dana",
    "option_c": "60 dana",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-05",
    "category": "VJERA",
    "question_text": "Koja tri sakramenta nose neizbrisivi duhovni biljeg (character) koji se zbog toga ne mogu ponoviti?",
    "option_a": "Krštenje, potvrda i sveti red",
    "option_b": "Krštenje, ženidba i pomirenje",
    "option_c": "Potvrda, euharistija i bolesničko pomazanje",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-06",
    "category": "VJERA",
    "question_text": "Koliko biblijskih čitanja, bez psalma, u pravilu ima nedjeljna misa u redovnom (godišnjem) liturgijskom vremenu?",
    "option_a": "2",
    "option_b": "3",
    "option_c": "4",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-07",
    "category": "VJERA",
    "question_text": "Kako se naziva dio euharistijske molitve u kojem se prizivlje Duh Sveti nad darove kruha i vina?",
    "option_a": "Epikleza",
    "option_b": "Doksologija",
    "option_c": "Sanctus",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-08",
    "category": "VJERA",
    "question_text": "Kako se naziva svečana molitva koja u misi neposredno slijedi nakon posvete, prije molitve „Oče naš“?",
    "option_a": "Doksologija",
    "option_b": "Agnus Dei",
    "option_c": "Sanctus",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-09",
    "category": "VJERA",
    "question_text": "Kako se naziva dio mise u kojem se kruh i vino donose i prinose na oltar, prije euharistijske molitve?",
    "option_a": "Prinošenje darova (ofertorij)",
    "option_b": "Doksologija",
    "option_c": "Epikleza",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-10",
    "category": "VJERA",
    "question_text": "Koliko je liturgijskih boja u redovitoj uporabi rimskog obreda (bijela, crvena, zelena, ljubičasta, ružičasta)?",
    "option_a": "4",
    "option_b": "5",
    "option_c": "6",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-11",
    "category": "VJERA",
    "question_text": "Koja tri objektivna uvjeta, prema katoličkom moralnom nauku, zajedno moraju biti ispunjena da bi grijeh bio smrtan?",
    "option_a": "Velika (teška) stvar, puna svijest i slobodan pristanak",
    "option_b": "Neznanje, dobra namjera i strah",
    "option_c": "Isključivo loša namjera počinitelja",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-12",
    "category": "VJERA",
    "question_text": "Koje se otajstvo slavi na Veliki četvrtak, uz sjećanje na Posljednju večeru?",
    "option_a": "Ustanovljenje Euharistije i svećeništva",
    "option_b": "Uzašašće Gospodinovo",
    "option_c": "Silazak Duha Svetoga",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "VJERA-13",
    "category": "VJERA",
    "question_text": "Na kojem je koncilu u 16. stoljeću konačno dogmatski utvrđen broj od sedam sakramenata?",
    "option_a": "Prvi vatikanski koncil",
    "option_b": "Tridentski koncil",
    "option_c": "Lateranski koncil",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-14",
    "category": "VJERA",
    "question_text": "Kojim se latinskim izrazom označava teološko načelo da valjanost sakramenta ne ovisi o osobnoj svetosti službenika koji ga dijeli?",
    "option_a": "Ex opere operato",
    "option_b": "Ex opere operantis",
    "option_c": "In persona Christi",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-15",
    "category": "VJERA",
    "question_text": "Koliko starozavjetnih čitanja punom (neskraćenom) obliku obreda može sadržavati Uskrsna vigilija, prije evanđelja?",
    "option_a": "Najviše 5",
    "option_b": "Najviše 7",
    "option_c": "Najviše 9",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-16",
    "category": "VJERA",
    "question_text": "Koje geste, prema obredniku, čine bitni (nužni) obredni čin pri ređenju svećenika?",
    "option_a": "Polaganje ruku i posvetna molitva biskupa",
    "option_b": "Pomazanje ulja na rukama novozaređenog",
    "option_c": "Predaja kaleža i patene novozaređenom",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-17",
    "category": "VJERA",
    "question_text": "Koje je godine promulgirana liturgijska reforma nakon Drugog vatikanskog koncila kojom je uveden novi red mise (Novus Ordo)?",
    "option_a": "1965.",
    "option_b": "1969.",
    "option_c": "1975.",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-18",
    "category": "VJERA",
    "question_text": "Kojim se latinskim izrazom označava teološko načelo „zakon molitve je zakon vjerovanja“?",
    "option_a": "Lex orandi, lex credendi",
    "option_b": "Extra ecclesiam nulla salus",
    "option_c": "Sola fide, sola gratia",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-19",
    "category": "VJERA",
    "question_text": "Koliko nepromjenjivih (stalnih) dijelova sadrži misni Ordinarij – Kyrie, Gloria, Credo, Sanctus i Agnus Dei?",
    "option_a": "4",
    "option_b": "5",
    "option_c": "6",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "VJERA-20",
    "category": "VJERA",
    "question_text": "Koja je stvarna prisutnost Isusa Krista u Presvetom Oltarskom Sakramentu prema katoličkom nauku o transupstancijaciji?",
    "option_a": "Simbolička, po analogiji s drugim sakramentima",
    "option_b": "Stvarna, potpuna prisutnost pod prilikama kruha i vina",
    "option_c": "Isključivo duhovna prisutnost bez ikakve promjene tvari",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "SV-01",
    "category": "SVECI",
    "question_text": "Tko je bio prvi papa Katoličke Crkve?",
    "option_a": "Petar",
    "option_b": "Pavao",
    "option_c": "Ivan",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "SV-02",
    "category": "SVECI",
    "question_text": "Koji je redovnički red osnovao sv. Franjo Asiški?",
    "option_a": "Franjevci",
    "option_b": "Dominikanci",
    "option_c": "Benediktinci",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "SV-03",
    "category": "SVECI",
    "question_text": "Koja je svetica poznata kao Majka Terezija, dobitnica Nobelove nagrade za mir?",
    "option_a": "Terezija Avilska",
    "option_b": "Terezija Calcuttska (Majka Terezija)",
    "option_c": "Terezija od Djeteta Isusa",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "SV-04",
    "category": "SVECI",
    "question_text": "Koji je papa proglasio Majku Tereziju svetom 2016. godine?",
    "option_a": "Benedikt XVI.",
    "option_b": "Franjo",
    "option_c": "Ivan Pavao II.",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-05",
    "category": "SVECI",
    "question_text": "Tko je autor djela „Ispovijesti“ i „O državi Božjoj“, jedan od najvećih crkvenih naučitelja Zapada?",
    "option_a": "Sv. Augustin",
    "option_b": "Sv. Jeronim",
    "option_c": "Sv. Toma Akvinski",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-06",
    "category": "SVECI",
    "question_text": "Koji je crkveni naučitelj preveo Bibliju na latinski jezik, poznat kao Vulgata?",
    "option_a": "Sv. Augustin",
    "option_b": "Sv. Jeronim",
    "option_c": "Sv. Ambrozije",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-07",
    "category": "SVECI",
    "question_text": "Koji je red, u sklopu reforme karmelićanskog reda, zajednički utemeljila sv. Tereza Avilska i sv. Ivan od Križa?",
    "option_a": "Bosonogi karmelićani",
    "option_b": "Franjevci kapucini",
    "option_c": "Uršulinke",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-08",
    "category": "SVECI",
    "question_text": "Kojim se nazivom (Doctor Angelicus) naziva sv. Toma Akvinski kao najveći srednjovjekovni teolog i filozof?",
    "option_a": "Anđeoski naučitelj",
    "option_b": "Zlatousti naučitelj",
    "option_c": "Serafski naučitelj",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-09",
    "category": "SVECI",
    "question_text": "Tko je zaštitnik Dubrovnika, po kojem grad slavi svoj dan 3. veljače?",
    "option_a": "Sv. Vlaho",
    "option_b": "Sv. Juraj",
    "option_c": "Sv. Nikola",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-10",
    "category": "SVECI",
    "question_text": "Koji je hrvatski svetac proglašen svetim 1970. godine, franjevac mučen i spaljen u Jeruzalemu?",
    "option_a": "Sv. Marko Križevčanin",
    "option_b": "Sv. Nikola Tavelić",
    "option_c": "Sv. Leopold Mandić",
    "correct_answer": "B",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "SV-11",
    "category": "SVECI",
    "question_text": "Koji je crkveni naučitelj poznat kao „Doctor Mysticus“ i autor djela „Tamna noć duše“?",
    "option_a": "Sv. Ivan od Križa",
    "option_b": "Sv. Bonaventura",
    "option_c": "Sv. Bernard iz Clairvauxa",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "SV-12",
    "category": "SVECI",
    "question_text": "U kojem je stoljeću, prema uobičajenoj dataciji njegova života (oko 480. – 547.), djelovao sv. Benedikt Nursijski, otac zapadnog monaštva?",
    "option_a": "4./5. stoljeće",
    "option_b": "5./6. stoljeće",
    "option_c": "8./9. stoljeće",
    "correct_answer": "B",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "SV-13",
    "category": "SVECI",
    "question_text": "Koji je papa 1970. godine proglasio sv. Terezu Avilsku i sv. Katarinu Sijensku prvim ženama-naučiteljicama Crkve?",
    "option_a": "Pavao VI.",
    "option_b": "Ivan XXIII.",
    "option_c": "Pio XII.",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "SV-14",
    "category": "SVECI",
    "question_text": "Koji je istočni crkveni otac poznat kao „Zlatousti“ (Chrysostom) zbog svoje besjedničke vještine?",
    "option_a": "Ivan Zlatousti",
    "option_b": "Bazilije Veliki",
    "option_c": "Grgur Nazijanski",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "SV-15",
    "category": "SVECI",
    "question_text": "Kako se naziva redovnička obitelj koju je sv. Benedikt utemeljio, čije je geslo „Ora et labora“ (Moli i radi)?",
    "option_a": "Red sv. Benedikta (benediktinci)",
    "option_b": "Cistercitski red",
    "option_c": "Trapistički red",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MARIJA-01",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koliko molitava „Zdravo Marijo“ sadrži jedna desetica krunice?",
    "option_a": "5",
    "option_b": "10",
    "option_c": "12",
    "correct_answer": "B",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "MARIJA-02",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koja se molitva moli na početku svake desetice krunice, prije deset „Zdravo Marijo“?",
    "option_a": "Oče naš",
    "option_b": "Slava Ocu",
    "option_c": "Vjerovanje",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "MARIJA-03",
    "category": "MARIJA_KRUNICA",
    "question_text": "Kako hrvatska pučka pobožnost naziva blagdan Marijina uznesenja, 15. kolovoza?",
    "option_a": "Velika Gospa",
    "option_b": "Mala Gospa",
    "option_c": "Gospa Kandelora",
    "correct_answer": "A",
    "difficulty": "EASY",
    "active": true
  },
  {
    "id": "MARIJA-04",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koja se skupina otajstava krunice tradicionalno moli nedjeljom (izvan korizme i posebnih vremena)?",
    "option_a": "Slavna otajstva",
    "option_b": "Radosna otajstva",
    "option_c": "Žalosna otajstva",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MARIJA-05",
    "category": "MARIJA_KRUNICA",
    "question_text": "U kojem je apostolskom pismu papa Ivan Pavao II. 2002. godine uveo otajstva svjetla u krunicu?",
    "option_a": "Rosarium Virginis Mariae",
    "option_b": "Redemptoris Mater",
    "option_c": "Marialis Cultus",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MARIJA-06",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koji se katolički blagdan slavi 2. veljače, vezan uz Isusovo prikazanje u hramu?",
    "option_a": "Prikazanje Gospodinovo (Svijećnica)",
    "option_b": "Navještenje",
    "option_c": "Pohod Marijin",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MARIJA-07",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koji dogmatski naslov Drugi vatikanski koncil pridaje Mariji u dokumentu Lumen gentium?",
    "option_a": "Majka Crkve",
    "option_b": "Kraljica neba",
    "option_c": "Zvijezda mora",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MARIJA-08",
    "category": "MARIJA_KRUNICA",
    "question_text": "Kako se naziva blagdan kad je Marija, prema Evanđelju po Luki, posjetila svoju rođakinju Elizabetu?",
    "option_a": "Pohod Marijin",
    "option_b": "Gospa od Zdravlja",
    "option_c": "Gospa Karmelska",
    "correct_answer": "A",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MARIJA-09",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koliko ukupno molitava „Zdravo Marijo“ sadrži puna krunica od svih 20 otajstava (4 skupine po 5 desetica)?",
    "option_a": "100",
    "option_b": "150",
    "option_c": "200",
    "correct_answer": "C",
    "difficulty": "MEDIUM",
    "active": true
  },
  {
    "id": "MARIJA-10",
    "category": "MARIJA_KRUNICA",
    "question_text": "Kojim je apostolskim dokumentom papa Pio XII. 1950. godine dogmatski proglasio Marijino uznesenje na nebo dušom i tijelom?",
    "option_a": "Munificentissimus Deus",
    "option_b": "Ineffabilis Deus",
    "option_c": "Redemptoris Mater",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MARIJA-11",
    "category": "MARIJA_KRUNICA",
    "question_text": "Kojom je apostolskom konstitucijom papa Pio IX. 1854. godine proglasio dogmu o Bezgrješnom začeću?",
    "option_a": "Ineffabilis Deus",
    "option_b": "Munificentissimus Deus",
    "option_c": "Pastor Aeternus",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MARIJA-12",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koji naziv nosi jedna od najstarijih poznatih marijanskih molitava, „Pod tvoju zaštitu bježimo“, datirana u 3. stoljeće?",
    "option_a": "Sub tuum praesidium",
    "option_b": "Salve Regina",
    "option_c": "Ave Maris Stella",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MARIJA-13",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koji je francuski svetac autor djela „Rasprava o istinskoj pobožnosti prema Presvetoj Djevici Mariji“?",
    "option_a": "Sv. Ljudevit Grignion Montfortski",
    "option_b": "Sv. Alfons Liguori",
    "option_c": "Sv. Bernard iz Clairvauxa",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MARIJA-14",
    "category": "MARIJA_KRUNICA",
    "question_text": "Kojim se latinskim teološkim nazivom označava Marijino sudioništvo u djelu otkupljenja, izraz koji Crkva ne rabi kao definiranu dogmu?",
    "option_a": "Corredemptrix",
    "option_b": "Mediatrix",
    "option_c": "Advocata",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  },
  {
    "id": "MARIJA-15",
    "category": "MARIJA_KRUNICA",
    "question_text": "Koje se hrvatsko svetište kraj Makarske naziva „Gospa od Zdravlja“?",
    "option_a": "Vepric",
    "option_b": "Aljmaš",
    "option_c": "Trsat",
    "correct_answer": "A",
    "difficulty": "HARD",
    "active": true
  }
];